---
title: "Hockey Bootstrap and Cross Validation"
author: "Nicholas Jacob"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
data = read.csv('https://raw.githubusercontent.com/nurfnick/RTest/main/hockey.csv')
library(boot)
```

This is a continuation of this project <<https://rpubs.com/nurfnick/720194>

## Bootstrapping

```{r bootFullMean}
set.seed(43)
samp_mean <- function(x, i) {
  mean(x[i])
}


GP <- na.omit(data$GP) 
results <- boot(GP, samp_mean, 100)
plot(results)
```

```{r}
boot.ci(results, type="perc")
```
```{r}
t.test(GP, mu = 4)
```
START HERE>>>>
$$
t = \frac{\mu-\overline x}{SE}
$$
```{r}
results$t0
```


```{r}
SE = sd(results$t)
c(results$t0-2*SE,results$t0+2*SE)
```

```{r}
t = (3.5-results$t0)/SE

1-pt(t,99)
```

```{r}
mean(3.5<=results$t)
```

```{r}
data

```

```{r}


data$GP[is.na(data$GP)] <- 0

data$GP
```

```{r}
samp_min <- function(x, i) {
  min(x[i])
}

results2 <- boot(data$GP,samp_min, R = 10000)
plot(results2)
```

```{r}
xbar = mean(results2$t)
s = sd(results2$t)
c(xbar - 2*s,xbar + 2*s)
```

```{r}
boot.ci(results2, type = "perc")
```

```{r}
mean(0 == results2$t)
```
%%%%Start Here

## Cross Validation

```{r}
library(caret)
data$W[is.na(data$W)] <- 0
data$PTS[is.na(data$PTS)] <- 0

trainingSamples <- createDataPartition(data$Rk ,p=.66,list = FALSE)
trainingSamples
```

```{r}
trainData <- data[trainingSamples,]
testData <- data[-trainingSamples,]
testData
```

```{r}
model <- lm(W ~ PTS , data = trainData)
summary(model)
```



```{r}
data[trainingSamples,'Test_Train'] <- "Train"
data[-trainingSamples,'Test_Train'] <- "Test"
data$Test_Train
```

```{r}
col.rainbow <- rainbow(2)
palette(col.rainbow)
plot(data$PTS,data$W,pch =19,col = as.factor(data$Test_Train))
abline(model)
```

```{r}
library(ggplot2)
ggplot(data = data, mapping = aes(PTS,W,color = Test_Train))+
  geom_jitter() +
  geom_smooth(method = lm)
```

```{r}
pre <- predict(model,data[-trainingSamples,])
pre
```

```{r}
R2(pre,data[-trainingSamples,"W"]  )
```
%%%Start Here


```{r}
train.control <- trainControl(method = "cv", number = 10)
model <- train(W ~ PTS, data = data, 
               method = "lm",
               trControl = train.control)
# Summarize the results
print(model)
```

```{r}
summary(model)
```

